version: "3.8"

services:
  vote:
    build: ./vote
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - redis
      - database

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - redis
      - database

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/initdb:/docker-entrypoint-initdb.d


volumes:
  pgdata:
