name: Deploy to Staging

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: [self-hosted, staging]

    steps:
    - uses: actions/checkout@v3

    - name: Deploy using Docker Compose
      run: |
        cd ${{ github.workspace }}
        docker compose -f docker-compose.staging.yml up -d --build
