name: Health Check

on:
  schedule:
    - cron: '*/30 * * * *'  # Cada 30 minutos

jobs:
  health:
    runs-on: [self-hosted, staging]  # ✔️ Usa la VM Vagrant como runner

    steps:
    - name: Esperar que vote se inicie
      run: sleep 10
      
    - name: Run health check
      run: curl -f http://localhost:5000 || exit 1

